### ISSUE TITLE
[New operator] Assess homogeneity of variance

### ISSUE THREAD

**Issue by makostadima** [tercen/app-library#189]
I showed to one of our users the compare_means operator and they asked me if we have one that assesses the variances between groups, so that they know what to use in the compare_means operator's settings.

@agouy suggested through slack a F-test. Maybe a more generic version like in *compare_means* operator would be nice so that we can do that also in datasets that ren't normally distibuted.

**Comment by agouy** [comment]
Implemented in https://github.com/tercen/levene_test_operator/releases/tag/0.0.1
