### ISSUE TITLE
Failed test: flowcut_operator [68d544da]

### ISSUE THREAD

**Issue by agouy** [tercen/app-library#19]
The unit test associated with this operator has failed. If you would like this operator to be part of the App Library, the test must be fixed.

Version: 0.1.3

```
ServiceError({statusCode: 400, error: run.operator.exit.code.143, reason: Failed to run operator, exit code = 143
--ERR--
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
})
```

Note: This issue has automatically been created by Tercen's operator sentinel.

**Comment by lucaslelann** [comment]
Fixed in 0.1.6
