### ISSUE TITLE
Add a unit test to kmeans_operator [a93db251]

### ISSUE THREAD

**Issue by agouy** [tercen/app-library#60]
There is no unit test associated with this operator (https://github.com/tercen/kmeans_operator). If you would like this operator to be part of the App Library, it must include [continuous integration workflows](https://tercen.github.io/developers_guide/continuous-integration.html).

Note: This issue has automatically been created by Tercen's operator sentinel.

**Comment by agouy** [comment]
@lucaslelann this one would be useful

**Comment by lucaslelann** [comment]
fixed in 0.1.0
