### ISSUE TITLE
Add a unit test to multiplybyconstant_operator [a31f35b7]

### ISSUE THREAD

**Issue by agouy** [tercen/app-library#63]
There is no unit test associated with this operator (https://github.com/tercen/multiplybyconstant_operator). If you would like this operator to be part of the App Library, it must include [continuous integration workflows](https://tercen.github.io/developers_guide/continuous-integration.html).

Note: This issue has automatically been created by Tercen's operator sentinel.

**Comment by lucaslelann** [comment]
fix in v0.1.0
