### ISSUE TITLE
Add a unit test to read_png_operator [ded601f1]

### ISSUE THREAD

**Issue by agouy** [tercen/app-library#74]
There is no unit test associated with this operator (https://github.com/tercen/read_png_operator). If you would like this operator to be part of the App Library, it must include [continuous integration workflows](https://tercen.github.io/developers_guide/continuous-integration.html).

Note: This issue has automatically been created by Tercen's operator sentinel.

**Comment by lucaslelann** [comment]
Done in v0.1.0
